sudo: required

language: java

services:
  - docker

jdk:
  - oraclejdk8

script:
  - docker build -t easyframe/easyframe-demo .

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push easyframe/easyframe-demo;
    fi