version: '3'
services:
  easyframe-demo:
    image: easyframe/easyframe-demo:latest
    stdin_open: true
    # 禁用tty,否则日志输出到Logstash会乱码
    # tty: true
    ports:
      - 28080:28080/tcp
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SPRING_CLOUD_CONFIG_ENABLED: ${SPRING_CLOUD_CONFIG_ENABLED}
      SPRING_CLOUD_CONFIG_URI: ${SPRING_CLOUD_CONFIG_URI}
      SPRING_JACKSON_SERIALIZATION_INDENT_OUTPUT: "true"
    networks:
      - easyframe
    volumes:
      - /etc/localtime:/etc/localtime:ro
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 60s
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 300
      resources:
        limits:
          cpus: "1"
          memory: "2048M"
    healthcheck:
      test: ["CMD", "wget", "-q", "http://localhost:28080/health", "-O", "/dev/null"]
      interval: 30s
      timeout: 5s
      retries: 5
networks:
  easyframe:
    external: true