server:
  port: 28080
info:
  easyframe:
    description: EasyFrame-Demo
    url: https://github.com/easyframe/easyframe-demo
    build-by: linzhaoming
management:
  security:
    enabled: false

spring:
  application:
    name: easyframe-demo
  profiles:
    active: dev

# [dev] Environment
---
spring:
  profiles: dev
logging:
  level:
    org.springframework.cloud.commons.util.InetUtils: TRACE

# [test] Environment
---
spring:
  profiles: test

# [staging] Environment
---
spring:
  profiles: staging

# [prod] Environment
---
spring:
  profiles: prod